### ISSUE TITLE
dependencies distributed by packages

### ISSUE THREAD

**Issue by miferco97** [aerostack2-developers/aerostack2#2]

**Comment by miferco97** [comment]
the installer located in ```installers/install_package_dependencies.py``` must work, check if each package contains an installer with a file called ```install_<whatever>.bash``` if it is needed

**Comment by pariaspe** [comment]
Explore using `rosdep` instead [[1]](https://docs.ros.org/en/humble/Tutorials/Intermediate/Rosdep.html) [[2]](http://wiki.ros.org/rosdep). 
- Add python3-rosdep to `install_core_dependencies.bash`
- Check package.xml --> eigen3 [[3]](https://github.com/ros2/eigen3_cmake_module).

**Comment by pariaspe** [comment]
Current `install_core_dependencies.bash`:
```
sudo apt update
# utils
sudo apt install tmux python3-vcstool -y

# libs
sudo apt install libyaml-cpp* -y &&\
sudo apt install libeigen3-dev -y

# python dependencies
sudo apt install python3-pip python3-testresources -y && \
sudo apt install python3-colcon-common-extensions -y

# ros2 dependencies

sudo apt install ros-${ROS_DISTRO}-ament-cmake-clang-format -y &&\
sudo apt install ros-${ROS_DISTRO}-eigen3-cmake-module -y  && \
sudo apt install ros-${ROS_DISTRO}-geographic-msgs -y 
#sudo apt install libgeographic-dev geographiclib-tools -y &&
```
Dependencies found in ROS Index:
- `libyaml-cpp*` --> [yaml-cpp](https://index.ros.org/d/yaml-cpp)
- `libeigen3-dev` --> [eigen](https://index.ros.org/d/eigen)
- `python3-colcon-common-extensions` --> [python3-colcon-common-extensions](https://index.ros.org/d/python3-colcon-common-extensions)
- `ament-cmake-clang-format` --> [ament-cmake-clang-format](https://index.ros.org/p/ament_cmake_clang_format/github-ament-ament_lint#humble)
- `eigen3-cmake-module` --> [eigen3-cmake-module](https://index.ros.org/p/eigen3_cmake_module)
- `geographic-msgs` --> [geographic-msgs](https://index.ros.org/p/geographic_msgs/github-ros-geographic-info-geographic_info#humble)
- `libgeographic-dev` --> [geographiclib](https://index.ros.org/d/geographiclib)
- ~`python3-testresources` **missing**.~ NOT NEEDED.

Then, script can be simplified into:
```
sudo apt update
# utils
sudo apt install tmux python3-vcstool python3-rosdep python3-pip -y
```
